//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UploadPhoto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int id { get; set; }
        public string personalId { get; set; }
        public string name { get; set; }
        public Nullable<int> id_profession { get; set; }
        public byte[] photo { get; set; }
    
        public virtual Profession Profession { get; set; }
    }
}
